propel:
  database:
      connections:
          defaultdb:
              adapter: mysql
              classname: Propel\Runtime\Connection\ConnectionWrapper
              dsn: "mysql:host=127.0.0.1;dbname=donationdb;port=3306"
              user: username
              password: password
              attributes:
  runtime:
      defaultConnection: defaultdb
      connections:
          - defaultdb
  generator:
      defaultConnection: defaultdb
      connections:
          - defaultdb

  paths:
      projectDir:  ../
      # The directory where Propel expects to find your `schema.xml` file.
      schemaDir: db

      # The directory where Propel should output classes, sql, config, etc.
      # Default value is current path #
      outputDir: db

      # The directory where Propel should output generated object model classes.
      phpDir: app/models

      # The directory where Propel should output the generated DDL (or data insert statements, etc.)
      sqlDir: db/migrations
